In [1]:
import sqlite3                                 
import pandas as pd                             
 
con = sqlite3.connect(r'C:\Users\faraz\OneDrive\Documents\SEM 3  AIRTEL DATA\Airtel_Telecom_Analysis\data\raw\airtel.db')  
 
def q(sql):                                     

    return pd.read_sql(sql, con)

In [2]:
def run_sql_file(path):
    with open(path, 'r') as f:
        script= f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [3]:
run_sql_file(r'C:\Users\faraz\OneDrive\Documents\SEM 3  AIRTEL DATA\Airtel_Telecom_Analysis\sql\01_Revenue_customer.sql')

ran C:\Users\faraz\OneDrive\Documents\SEM 3  AIRTEL DATA\Airtel_Telecom_Analysis\sql\01_Revenue_customer.sql

In [6]:
q("""
SELECT COUNT(*) AS total_customers,
ROUND(AVG(arpu_inr),2) AS average_recorded_arpu,
COUNT(DISTINCT arpu_inr) AS distinct_arpu_values
FROM customers;
""")

   total_customers  average_recorded_arpu  distinct_arpu_values
0            22000                 421.65                    13

In [9]:
q("""
SELECT 
    COUNT(*) AS customers_without_payments
FROM customers AS c
WHERE NOT EXISTS (
    SELECT 1
    FROM recharges AS r
    WHERE r.customer_id = c.customer_id
      AND r.recharge_date >= '2025-01-01'
      AND r.recharge_date < '2025-07-01');
""")

   customers_without_payments
0                        3711